[deploy]
startCommand = "gunicorn run:app --bind 0.0.0.0:8000 --worker-class gthread --threads 4 --workers 1 --timeout 180"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
healthcheckPath = ""
healthcheckTimeout = 300

[[services]]
internalPort = 8000
